### ISSUE TITLE
Error when doing "west update"

### ISSUE THREAD

**Issue by E3V3A** [NordicPlayground/fw-nrfconnect-mbedtls#1]
I get the following error when doing "west update".

![cmd_2019-09-04_18-12-53](https://user-images.githubusercontent.com/194392/64274375-c9a72680-cf32-11e9-8b51-9e2a3e326244.png)

Any ideas why this happen?

**Comment by mbolivar** [comment]
> Any ideas why this happen?

This is confusing.

West maintains a `manifest-rev` git ref in each project each time `west update` is run, which points at the exact revision used in west.yml. What's happening here is that somehow this ref was removed from your repository. I'm not sure how this could happen, as west recreates this ref if it doesn't exist. I  have tried all of the following with the latest `nrf`, version 561986f5f1a12322ac6d2a72170ca59363bebcf2:

- deleting the file `ncs/mbedtls/.git/refs/heads/manifest-rev` and running `west update`
- deleting the `ncs/mbedtls` directory entirely and running `west update`
- deliberately introducing an ambiguous ref with `git update-ref manifest-rev HEAD` in the mbedtls repository and running `west update`

All of these worked and correctly made sure the mbedtls repository is at version 53546ea099f6f53d0be653a64accd250e170337f.

Some questions for you:

- Can you retry on west 0.6.2? 
- What revision is `ncs/nrf` at?

You might want to try moving your current mbedtls repository somewhere else (`mv mbedtls mbedtls-backup`) and running `west update` again to see if that fixes it.

**Comment by mbolivar** [comment]
I can't even reproduce this on 0.6.1.

**Comment by E3V3A** [comment]
Yeah, it's all good now. Apparently (lost reference) there was some developer who forgot something, and promptly fixed it. So after I did the following, everything started working.

```bash
cd ${NORDICS}/ncs/nrf
git checkout -f master
git pull
git checkout v1.0.0
west update
```
